Repository PreOnBoarding-Team17/Week3_MainPage, pull requests merged in 2022-02, with the labels that each got.

#9 [현다솜] feat: navigation 구현
  components/common/Navigation/index.tsx
  pages/_app.tsx
  pages/index.tsx
  public/assets/cart.png
  public/assets/hamburger.png
  public/assets/logo-black.png
  public/assets/logo-white.png
  pull_request_template.md
  styles/Mixin.tsx
Labels: :joystick: 기능, 📱 UI

#10 [현다솜] feat: DownloadBtn 컴포넌트 구현 + prettier 적용
  .prettierrc.json
  components/Main/index.tsx
  components/common/DownloadButton/index.tsx
  components/common/Navigation/index.tsx
  package.json
  pages/index.tsx
  public/assets/mini-logo-white.png
  styles/GlobalStyles.tsx
  styles/Mixin.tsx
  yarn.lock
Labels: :joystick: 기능, 📱 UI

#13 [정인권] feat: About 컴포넌트 구현
  components/About/index.tsx
  components/Main/index.tsx
  package.json
  pages/index.tsx
  public/assets/main-tablet-bg.jpg
  public/assets/white-logo.png
  yarn.lock
Labels: :joystick: 기능, 📱 UI

#15 [현다솜] feat: useMedia hooks 추가 + prettier 수정 및 적용
  .prettierrc.json
  components/About/index.tsx
  components/LiveVideo/index.tsx
  components/Main/index.tsx
  components/common/DownloadButton/index.tsx
  components/common/Navigation/index.tsx
  pages/index.tsx
  styles/GlobalStyles.tsx
  styles/Mixin.tsx
  utils/constants/index.ts
  utils/hooks/index.tsx
  utils/hooks/useMedia.tsx
Labels: :joystick: 기능, ⚙️ 설정

#19 [황상섭] feat: ReadingDiary 컴포넌트 구현
  components/ReadingDiary/index.tsx
  pages/index.tsx
  public/assets/ReadingBooks/tablet.png
  public/assets/ReadingDiary/Diary.png
Labels: :joystick: 기능, 📱 UI

#21 [정인권] feat: Footer 컴포넌트 구현
  components/About/index.tsx
  components/Main/index.tsx
  components/common/Footer/index.tsx
  pages/index.tsx
  public/assets/footer/blog.png
  public/assets/footer/instagram.png
  public/assets/main/main-bg.jpg
  public/assets/main/main-tablet-bg.jpg
  public/assets/main/star.png
  utils/hooks/index.tsx
  utils/hooks/useMedia.tsx
Labels: :joystick: 기능, 📱 UI

#23 [현다솜] feat: CheckedBooks 컴포넌트 구현 + Navigation 컴포넌트 수정
  components/CheckedBooks/CheckedBookImage.tsx
  components/CheckedBooks/CheckedBookItem.tsx
  components/CheckedBooks/index.tsx
  components/common/Navigation/index.tsx
  pages/index.tsx
Labels: 🐞 버그, :joystick: 기능, 📱 UI

#25 [황상섭] feat: BestSeller 컴포넌트 구현
  components/BestSeller/index.tsx
  pages/index.tsx
  public/assets/BestSeller/img_book_1.png
  public/assets/BestSeller/img_book_10.png
  public/assets/BestSeller/img_book_11.png
  public/assets/BestSeller/img_book_12.png
  public/assets/BestSeller/img_book_13.png
  public/assets/BestSeller/img_book_14.png
  public/assets/BestSeller/img_book_15.png
  public/assets/BestSeller/img_book_2.png
  public/assets/BestSeller/img_book_3.png
  public/assets/BestSeller/img_book_4.png
  public/assets/BestSeller/img_book_5.png
  public/assets/BestSeller/img_book_6.png
  public/assets/BestSeller/img_book_7.png
  public/assets/BestSeller/img_book_8.png
  public/assets/BestSeller/img_book_9.png
  public/assets/books/img_book_1.png
  public/assets/books/img_book_10.png
  public/assets/books/img_book_11.png
  public/assets/books/img_book_12.png
  public/assets/books/img_book_13.png
  public/assets/books/img_book_14.png
  public/assets/books/img_book_15.png
  public/assets/books/img_book_16.png
  public/assets/books/img_book_17.png
  public/assets/books/img_book_18.png
  public/assets/books/img_book_19.png
  public/assets/books/img_book_2.png
  public/assets/books/img_book_20.png
  public/assets/books/img_book_3.png
  public/assets/books/img_book_4.png
  public/assets/books/img_book_5.png
  public/assets/books/img_book_6.png
  public/assets/books/img_book_7.png
  public/assets/books/img_book_8.png
  public/assets/books/img_book_9.png
Labels: :joystick: 기능, 📱 UI

#28 [황상섭] feat: Feature 컴포넌트 구현
  components/BestSeller/BookList.tsx
  components/BestSeller/index.tsx
  components/Feature/Card.tsx
  components/Feature/index.tsx
  pages/index.tsx
  public/assets/Feature/Icon_1.png
  public/assets/Feature/Icon_2.png
  public/assets/Feature/Icon_3.png
  public/assets/Feature/Image.png
  styles/GlobalStyles.tsx
Labels: :joystick: 기능, ⬆️ 리팩토링, 📱 UI

#29 [정인권] feat: Download 컴포넌트 구현
  components/Download/index.tsx
  pages/index.tsx
  public/assets/download/coupon-pc.png
  public/assets/download/coupon-phone.png
  public/assets/download/coupon-tablet.png
  public/assets/download/download-btn.png
  public/assets/download/logo-white.png
  public/assets/white-logo.png
Labels: :joystick: 기능, 📱 UI

#30 [황상섭] refactor: 상수 constants 폴더로 이동 및 불필요한 css 코드 삭제
  components/BestSeller/index.tsx
  components/Feature/Card.tsx
  components/Feature/index.tsx
  components/LiveVideo/index.tsx
  components/ReadingBooks/index.tsx
  components/ReadingDiary/index.tsx
  components/common/Text/index.tsx
  components/common/Title/index.tsx
  styles/GlobalStyles.tsx
  utils/constants/index.ts
Labels: ⬆️ 리팩토링

#32 [정인권] feat: Scroll Event 설정 및 일부 구현
  components/About/index.tsx
  components/Download/index.tsx
  components/Main/index.tsx
  package.json
  pages/_app.tsx
  public/assets/About/second-logo.gif
  public/assets/main/mouse.png
  utils/constants/index.ts
  yarn.lock
Labels: :joystick: 기능

#33 [정인권] feat: Navigation Scroll Event 구현
  components/common/Navigation/index.tsx
  pages/_app.tsx
  public/assets/Navigation/logo-black.png
  public/assets/Navigation/logo-white.png
  utils/hooks/useScroll.tsx
Labels: :joystick: 기능

#34 [현다솜] feat: Review 컴포넌트 구현
  .babelrc
  components/Recommendation/index.tsx
  components/Review/BookSwiper.tsx
  components/Review/ReviewItem.tsx
  components/Review/index.tsx
  package.json
  pages/index.tsx
  public/assets/Image 22.png
  public/assets/background-book.png
  public/assets/kids-circle/kids0.png
  public/assets/kids-circle/kids6.png
  public/assets/next.png
  public/assets/prev.png
  public/assets/yellow-logo-low-opacity.png
  styles/GlobalStyles.tsx
  utils/constants/index.ts
  yarn.lock
Labels: :joystick: 기능, 📱 UI

#37 [현다솜] feat: CheckedBooks 순차재생 애니메이션 추가
  components/CheckedBooks/CheckedBookImage.tsx
  components/CheckedBooks/CheckedBookItem.tsx
  utils/constants/index.ts
Labels: :joystick: 기능

#38 [황상섭] feat: 스크롤 애니메이션 추가
  components/CheckedBooks/CheckedBookItem.tsx
  components/CheckedBooks/index.tsx
  components/Download/index.tsx
  components/Feature/Card.tsx
  components/Feature/index.tsx
  components/LiveVideo/index.tsx
  components/ReadingDiary/index.tsx
  components/common/DownloadButton/index.tsx
  components/common/Footer/index.tsx
  components/common/Navigation/index.tsx
  components/common/Text/index.tsx
  components/common/Title/index.tsx
  pages/_app.tsx
Labels: :joystick: 기능, 📱 UI

#39 [정인권] feat: scroll event gif delay 작동 구현
  components/CheckedBooks/CheckedBookImage.tsx
  components/CheckedBooks/CheckedBookItem.tsx
  pages/_app.tsx
  public/assets/check-animation/first.png
  public/assets/check-animation/second.png
  public/assets/check-animation/third.png
  utils/constants/index.ts
Labels: :joystick: 기능

#40 [현다솜] feat: Download 컴포넌트 애니메이션 추가
  components/Download/index.tsx
  public/assets/download/triangle.png
Labels: :joystick: 기능

#41 [현다솜] refactor: CheckedBooks margin 조정 + Navigation black icon 추가
  components/CheckedBooks/CheckedBookImage.tsx
  components/CheckedBooks/CheckedBookItem.tsx
  components/Review/ReviewItem.tsx
  components/common/Navigation/index.tsx
  public/assets/cart-black.png
  public/assets/hamburger-black.png
Labels: ⬆️ 리팩토링
